CREATE TABLE [dbo].[USER]
(
	[ID] BIGINT NOT NULL PRIMARY KEY  , 
    [FIRST_NAME] NCHAR(10) NULL, 
    [LAST_NAME] NCHAR(10) NULL, 
    [BIRTH_DATE] DATETIME NULL, 
    [STREET] NCHAR(30) NULL, 
    [CITY] NCHAR(10) NULL, 
    [POSTAL_CODE] NCHAR(10) NULL
)
