CREATE TABLE [dbo].[USER]
(
	[ID] BIGINT NOT NULL PRIMARY KEY  , 
    [FIRST_NAME] NVARCHAR(10) NULL, 
    [LAST_NAME] NVARCHAR(10) NULL, 
    [EMAIL] NVARCHAR(10) NULL, 
    [PASSWORD] NVARCHAR(20) NULL, 
    [BIRTH_DATE] DATETIME NULL, 
    [STREET] NVARCHAR(30) NULL, 
    [CITY] NVARCHAR(10) NULL, 
    [POSTAL_CODE] NVARCHAR(10) NULL
)
